/**
 * TweakCN Theme Presets for Vuecraft
 * Converted from https://github.com/jnsahaj/tweakcn
 */

export interface TweakcnThemeStyle {
  background: string
  foreground: string
  card: string
  'card-foreground': string
  popover: string
  'popover-foreground': string
  primary: string
  'primary-foreground': string
  secondary: string
  'secondary-foreground': string
  muted: string
  'muted-foreground': string
  accent: string
  'accent-foreground': string
  destructive: string
  'destructive-foreground': string
  border: string
  input: string
  ring: string
  'chart-1'?: string
  'chart-2'?: string
  'chart-3'?: string
  'chart-4'?: string
  'chart-5'?: string
  sidebar?: string
  'sidebar-foreground'?: string
  'sidebar-primary'?: string
  'sidebar-primary-foreground'?: string
  'sidebar-accent'?: string
  'sidebar-accent-foreground'?: string
  'sidebar-border'?: string
  'sidebar-ring'?: string
  radius?: string
}

export interface TweakcnPreset {
  id: string
  label: string
  description: string
  category:
    | 'professional'
    | 'colorful'
    | 'nature'
    | 'warm'
    | 'cool'
    | 'brand'
    | 'retro'
    | 'monochrome'
  tags: string[]
  styles: {
    light: TweakcnThemeStyle
    dark: TweakcnThemeStyle
  }
}

export const TWEAKCN_PRESETS: TweakcnPreset[] = [
  {
    id: 'modern-minimal',
    label: 'Modern Minimal',
    description: 'Clean blue professional theme',
    category: 'professional',
    tags: ['blue', 'clean', 'minimal', 'professional'],
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        radius: '0.375rem',
      },
    },
  },
  {
    id: 'violet-bloom',
    label: 'Violet Bloom',
    description: 'Purple with custom shadows',
    category: 'colorful',
    tags: ['purple', 'violet', 'vibrant', 'modern'],
    styles: {
      light: {
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        'destructive-foreground': '#ffffff',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#7033ff',
        radius: '1.4rem',
      },
      dark: {
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        radius: '1.4rem',
      },
    },
  },
  {
    id: 't3-chat',
    label: 'T3 Chat',
    description: 'Mauve/pink conversation palette',
    category: 'colorful',
    tags: ['pink', 'mauve', 'chat', 'modern'],
    styles: {
      light: {
        background: '#faf5fa',
        foreground: '#501854',
        card: '#faf5fa',
        'card-foreground': '#501854',
        popover: '#ffffff',
        'popover-foreground': '#501854',
        primary: '#a84370',
        'primary-foreground': '#ffffff',
        secondary: '#f1c4e6',
        'secondary-foreground': '#77347c',
        muted: '#f6e5f3',
        'muted-foreground': '#834588',
        accent: '#f1c4e6',
        'accent-foreground': '#77347c',
        destructive: '#ab4347',
        'destructive-foreground': '#ffffff',
        border: '#efbdeb',
        input: '#e7c1dc',
        ring: '#db2777',
        radius: '0.5rem',
      },
      dark: {
        background: '#221d27',
        foreground: '#d2c4de',
        card: '#2c2632',
        'card-foreground': '#dbc5d2',
        popover: '#100a0e',
        'popover-foreground': '#f8f1f5',
        primary: '#a3004c',
        'primary-foreground': '#efc0d8',
        secondary: '#362d3d',
        'secondary-foreground': '#d4c7e1',
        muted: '#28222d',
        'muted-foreground': '#c2b6cf',
        accent: '#463753',
        'accent-foreground': '#f8f1f5',
        destructive: '#301015',
        'destructive-foreground': '#ffffff',
        border: '#3b3237',
        input: '#3e343c',
        ring: '#db2777',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'twitter',
    label: 'Twitter',
    description: 'Social media inspired',
    category: 'brand',
    tags: ['twitter', 'blue', 'social', 'brand'],
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#0f1419',
        card: '#f7f8f8',
        'card-foreground': '#0f1419',
        popover: '#ffffff',
        'popover-foreground': '#0f1419',
        primary: '#1e9df1',
        'primary-foreground': '#ffffff',
        secondary: '#0f1419',
        'secondary-foreground': '#ffffff',
        muted: '#E5E5E6',
        'muted-foreground': '#0f1419',
        accent: '#E3ECF6',
        'accent-foreground': '#1e9df1',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#e1eaef',
        input: '#f7f9fa',
        ring: '#1da1f2',
        radius: '1.3rem',
      },
      dark: {
        background: '#000000',
        foreground: '#e7e9ea',
        card: '#17181c',
        'card-foreground': '#d9d9d9',
        popover: '#000000',
        'popover-foreground': '#e7e9ea',
        primary: '#1c9cf0',
        'primary-foreground': '#ffffff',
        secondary: '#f0f3f4',
        'secondary-foreground': '#0f1419',
        muted: '#181818',
        'muted-foreground': '#72767a',
        accent: '#061622',
        'accent-foreground': '#1c9cf0',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#242628',
        input: '#22303c',
        ring: '#1da1f2',
        radius: '1.3rem',
      },
    },
  },
  {
    id: 'mocha-mousse',
    label: 'Mocha Mousse',
    description: 'Warm brown/tan palette',
    category: 'warm',
    tags: ['brown', 'tan', 'warm', 'cozy'],
    styles: {
      light: {
        background: '#F1F0E5',
        foreground: '#56453F',
        card: '#F1F0E5',
        'card-foreground': '#56453F',
        popover: '#FFFFFF',
        'popover-foreground': '#56453F',
        primary: '#A37764',
        'primary-foreground': '#FFFFFF',
        secondary: '#BAAB92',
        'secondary-foreground': '#ffffff',
        muted: '#E4C7B8',
        'muted-foreground': '#8A655A',
        accent: '#E4C7B8',
        'accent-foreground': '#56453F',
        destructive: '#1f1a17',
        'destructive-foreground': '#FFFFFF',
        border: '#BAAB92',
        input: '#BAAB92',
        ring: '#A37764',
        radius: '0.5rem',
      },
      dark: {
        background: '#2d2521',
        foreground: '#F1F0E5',
        card: '#3c332e',
        'card-foreground': '#F1F0E5',
        popover: '#3c332e',
        'popover-foreground': '#F1F0E5',
        primary: '#C39E88',
        'primary-foreground': '#2d2521',
        secondary: '#56453F',
        'secondary-foreground': '#F1F0E5',
        muted: '#56453F',
        'muted-foreground': '#C39E88',
        accent: '#56453F',
        'accent-foreground': '#F1F0E5',
        destructive: '#ab4347',
        'destructive-foreground': '#FFFFFF',
        border: '#56453F',
        input: '#56453F',
        ring: '#C39E88',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'bubblegum',
    label: 'Bubblegum',
    description: 'Vibrant pink & cyan',
    category: 'colorful',
    tags: ['pink', 'cyan', 'vibrant', 'playful'],
    styles: {
      light: {
        background: '#fff5f7',
        foreground: '#1a1a2e',
        card: '#ffffff',
        'card-foreground': '#1a1a2e',
        popover: '#ffffff',
        'popover-foreground': '#1a1a2e',
        primary: '#ff6b9d',
        'primary-foreground': '#ffffff',
        secondary: '#e0f4ff',
        'secondary-foreground': '#0ea5e9',
        muted: '#fce7f3',
        'muted-foreground': '#9f1239',
        accent: '#00d9ff',
        'accent-foreground': '#164e63',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#fda4af',
        input: '#fce7f3',
        ring: '#ff6b9d',
        radius: '1rem',
      },
      dark: {
        background: '#1a1a2e',
        foreground: '#fff5f7',
        card: '#2d2d44',
        'card-foreground': '#fff5f7',
        popover: '#2d2d44',
        'popover-foreground': '#fff5f7',
        primary: '#ff6b9d',
        'primary-foreground': '#1a1a2e',
        secondary: '#164e63',
        'secondary-foreground': '#00d9ff',
        muted: '#3d3d5c',
        'muted-foreground': '#fda4af',
        accent: '#00d9ff',
        'accent-foreground': '#ffffff',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#4d4d6a',
        input: '#3d3d5c',
        ring: '#ff6b9d',
        radius: '1rem',
      },
    },
  },
  {
    id: 'catppuccin',
    label: 'Catppuccin',
    description: 'Purple/blue harmony',
    category: 'colorful',
    tags: ['purple', 'blue', 'catppuccin', 'pastel'],
    styles: {
      light: {
        background: '#eff1f5',
        foreground: '#4c4f69',
        card: '#e6e9ef',
        'card-foreground': '#4c4f69',
        popover: '#e6e9ef',
        'popover-foreground': '#4c4f69',
        primary: '#8839ef',
        'primary-foreground': '#ffffff',
        secondary: '#dce0e8',
        'secondary-foreground': '#5c5f77',
        muted: '#ccd0da',
        'muted-foreground': '#6c6f85',
        accent: '#ea76cb',
        'accent-foreground': '#ffffff',
        destructive: '#d20f39',
        'destructive-foreground': '#ffffff',
        border: '#acb0be',
        input: '#bcc0cc',
        ring: '#8839ef',
        radius: '0.5rem',
      },
      dark: {
        background: '#1e1e2e',
        foreground: '#cdd6f4',
        card: '#313244',
        'card-foreground': '#cdd6f4',
        popover: '#313244',
        'popover-foreground': '#cdd6f4',
        primary: '#cba6f7',
        'primary-foreground': '#1e1e2e',
        secondary: '#45475a',
        'secondary-foreground': '#cdd6f4',
        muted: '#585b70',
        'muted-foreground': '#a6adc8',
        accent: '#f5c2e7',
        'accent-foreground': '#1e1e2e',
        destructive: '#f38ba8',
        'destructive-foreground': '#1e1e2e',
        border: '#6c7086',
        input: '#585b70',
        ring: '#cba6f7',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'graphite',
    label: 'Graphite',
    description: 'Monochromatic gray',
    category: 'monochrome',
    tags: ['gray', 'monochrome', 'minimal', 'professional'],
    styles: {
      light: {
        background: '#f5f5f5',
        foreground: '#262626',
        card: '#ffffff',
        'card-foreground': '#262626',
        popover: '#ffffff',
        'popover-foreground': '#262626',
        primary: '#525252',
        'primary-foreground': '#ffffff',
        secondary: '#e5e5e5',
        'secondary-foreground': '#404040',
        muted: '#d4d4d4',
        'muted-foreground': '#737373',
        accent: '#a3a3a3',
        'accent-foreground': '#171717',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#d4d4d4',
        input: '#e5e5e5',
        ring: '#525252',
        radius: '0.25rem',
      },
      dark: {
        background: '#171717',
        foreground: '#fafafa',
        card: '#262626',
        'card-foreground': '#fafafa',
        popover: '#262626',
        'popover-foreground': '#fafafa',
        primary: '#d4d4d4',
        'primary-foreground': '#171717',
        secondary: '#404040',
        'secondary-foreground': '#fafafa',
        muted: '#525252',
        'muted-foreground': '#a3a3a3',
        accent: '#737373',
        'accent-foreground': '#fafafa',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#525252',
        ring: '#d4d4d4',
        radius: '0.25rem',
      },
    },
  },
  {
    id: 'perpetuity',
    label: 'Perpetuity',
    description: 'Teal/cyan minimalist',
    category: 'cool',
    tags: ['teal', 'cyan', 'minimal', 'modern'],
    styles: {
      light: {
        background: '#f0fdfa',
        foreground: '#134e4a',
        card: '#ffffff',
        'card-foreground': '#134e4a',
        popover: '#ffffff',
        'popover-foreground': '#134e4a',
        primary: '#14b8a6',
        'primary-foreground': '#ffffff',
        secondary: '#ccfbf1',
        'secondary-foreground': '#0d9488',
        muted: '#99f6e4',
        'muted-foreground': '#0f766e',
        accent: '#5eead4',
        'accent-foreground': '#134e4a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#99f6e4',
        input: '#ccfbf1',
        ring: '#14b8a6',
        radius: '0.5rem',
      },
      dark: {
        background: '#042f2e',
        foreground: '#f0fdfa',
        card: '#134e4a',
        'card-foreground': '#f0fdfa',
        popover: '#134e4a',
        'popover-foreground': '#f0fdfa',
        primary: '#2dd4bf',
        'primary-foreground': '#042f2e',
        secondary: '#115e59',
        'secondary-foreground': '#ccfbf1',
        muted: '#0f766e',
        'muted-foreground': '#99f6e4',
        accent: '#0d9488',
        'accent-foreground': '#f0fdfa',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#0f766e',
        input: '#115e59',
        ring: '#2dd4bf',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'kodama-grove',
    label: 'Kodama Grove',
    description: 'Natural sage greens',
    category: 'nature',
    tags: ['green', 'sage', 'nature', 'forest'],
    styles: {
      light: {
        background: '#f5f7f4',
        foreground: '#2d3a2e',
        card: '#ffffff',
        'card-foreground': '#2d3a2e',
        popover: '#ffffff',
        'popover-foreground': '#2d3a2e',
        primary: '#5d7a5f',
        'primary-foreground': '#ffffff',
        secondary: '#e8ede8',
        'secondary-foreground': '#4a5f4c',
        muted: '#d4ddd5',
        'muted-foreground': '#5d7a5f',
        accent: '#8fae91',
        'accent-foreground': '#2d3a2e',
        destructive: '#c53030',
        'destructive-foreground': '#ffffff',
        border: '#c9d6ca',
        input: '#e8ede8',
        ring: '#5d7a5f',
        radius: '0.625rem',
      },
      dark: {
        background: '#1a211b',
        foreground: '#e8ede8',
        card: '#252d26',
        'card-foreground': '#e8ede8',
        popover: '#252d26',
        'popover-foreground': '#e8ede8',
        primary: '#8fae91',
        'primary-foreground': '#1a211b',
        secondary: '#3d4a3e',
        'secondary-foreground': '#e8ede8',
        muted: '#4a5f4c',
        'muted-foreground': '#a8c5aa',
        accent: '#5d7a5f',
        'accent-foreground': '#e8ede8',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#3d4a3e',
        input: '#4a5f4c',
        ring: '#8fae91',
        radius: '0.625rem',
      },
    },
  },
  {
    id: 'cosmic-night',
    label: 'Cosmic Night',
    description: 'Deep purple space',
    category: 'cool',
    tags: ['purple', 'space', 'dark', 'cosmic'],
    styles: {
      light: {
        background: '#faf5ff',
        foreground: '#3b0764',
        card: '#ffffff',
        'card-foreground': '#3b0764',
        popover: '#ffffff',
        'popover-foreground': '#3b0764',
        primary: '#9333ea',
        'primary-foreground': '#ffffff',
        secondary: '#f3e8ff',
        'secondary-foreground': '#6b21a8',
        muted: '#e9d5ff',
        'muted-foreground': '#7e22ce',
        accent: '#c084fc',
        'accent-foreground': '#3b0764',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#d8b4fe',
        input: '#f3e8ff',
        ring: '#9333ea',
        radius: '0.75rem',
      },
      dark: {
        background: '#0c0015',
        foreground: '#faf5ff',
        card: '#1a0a2e',
        'card-foreground': '#faf5ff',
        popover: '#1a0a2e',
        'popover-foreground': '#faf5ff',
        primary: '#a855f7',
        'primary-foreground': '#0c0015',
        secondary: '#3b0764',
        'secondary-foreground': '#e9d5ff',
        muted: '#581c87',
        'muted-foreground': '#d8b4fe',
        accent: '#7c3aed',
        'accent-foreground': '#faf5ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#581c87',
        input: '#3b0764',
        ring: '#a855f7',
        radius: '0.75rem',
      },
    },
  },
  {
    id: 'tangerine',
    label: 'Tangerine',
    description: 'Orange warm palette',
    category: 'warm',
    tags: ['orange', 'warm', 'vibrant', 'energetic'],
    styles: {
      light: {
        background: '#fffaf0',
        foreground: '#7c2d12',
        card: '#ffffff',
        'card-foreground': '#7c2d12',
        popover: '#ffffff',
        'popover-foreground': '#7c2d12',
        primary: '#f97316',
        'primary-foreground': '#ffffff',
        secondary: '#fed7aa',
        'secondary-foreground': '#c2410c',
        muted: '#ffedd5',
        'muted-foreground': '#9a3412',
        accent: '#fb923c',
        'accent-foreground': '#7c2d12',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fdba74',
        input: '#ffedd5',
        ring: '#f97316',
        radius: '0.5rem',
      },
      dark: {
        background: '#1c0a00',
        foreground: '#fff7ed',
        card: '#2a1508',
        'card-foreground': '#fff7ed',
        popover: '#2a1508',
        'popover-foreground': '#fff7ed',
        primary: '#fb923c',
        'primary-foreground': '#1c0a00',
        secondary: '#7c2d12',
        'secondary-foreground': '#fed7aa',
        muted: '#9a3412',
        'muted-foreground': '#fdba74',
        accent: '#ea580c',
        'accent-foreground': '#fff7ed',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#9a3412',
        input: '#7c2d12',
        ring: '#fb923c',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'supabase',
    label: 'Supabase',
    description: 'Green startup branding',
    category: 'brand',
    tags: ['green', 'supabase', 'brand', 'startup'],
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#1c1c1c',
        card: '#f8fafc',
        'card-foreground': '#1c1c1c',
        popover: '#ffffff',
        'popover-foreground': '#1c1c1c',
        primary: '#3ecf8e',
        'primary-foreground': '#1c1c1c',
        secondary: '#e2e8f0',
        'secondary-foreground': '#475569',
        muted: '#f1f5f9',
        'muted-foreground': '#64748b',
        accent: '#b3f0d4',
        'accent-foreground': '#065f46',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e2e8f0',
        input: '#f1f5f9',
        ring: '#3ecf8e',
        radius: '0.375rem',
      },
      dark: {
        background: '#1c1c1c',
        foreground: '#fafafa',
        card: '#2a2a2a',
        'card-foreground': '#fafafa',
        popover: '#2a2a2a',
        'popover-foreground': '#fafafa',
        primary: '#3ecf8e',
        'primary-foreground': '#1c1c1c',
        secondary: '#3f3f46',
        'secondary-foreground': '#fafafa',
        muted: '#27272a',
        'muted-foreground': '#a1a1aa',
        accent: '#065f46',
        'accent-foreground': '#b3f0d4',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#3f3f46',
        input: '#27272a',
        ring: '#3ecf8e',
        radius: '0.375rem',
      },
    },
  },
  {
    id: 'neo-brutalism',
    label: 'Neo Brutalism',
    description: 'High-contrast primary colors',
    category: 'retro',
    tags: ['brutalist', 'bold', 'high-contrast', 'retro'],
    styles: {
      light: {
        background: '#f5f5dc',
        foreground: '#000000',
        card: '#ffffff',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#ff6b6b',
        'primary-foreground': '#000000',
        secondary: '#4ecdc4',
        'secondary-foreground': '#000000',
        muted: '#ffe66d',
        'muted-foreground': '#000000',
        accent: '#95e1d3',
        'accent-foreground': '#000000',
        destructive: '#ff0000',
        'destructive-foreground': '#ffffff',
        border: '#000000',
        input: '#ffffff',
        ring: '#000000',
        radius: '0',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#f5f5dc',
        card: '#2a2a2a',
        'card-foreground': '#f5f5dc',
        popover: '#2a2a2a',
        'popover-foreground': '#f5f5dc',
        primary: '#ff6b6b',
        'primary-foreground': '#000000',
        secondary: '#4ecdc4',
        'secondary-foreground': '#000000',
        muted: '#3a3a3a',
        'muted-foreground': '#ffe66d',
        accent: '#95e1d3',
        'accent-foreground': '#000000',
        destructive: '#ff4444',
        'destructive-foreground': '#ffffff',
        border: '#f5f5dc',
        input: '#3a3a3a',
        ring: '#f5f5dc',
        radius: '0',
      },
    },
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Neon magenta/cyan',
    category: 'colorful',
    tags: ['neon', 'cyberpunk', 'magenta', 'cyan'],
    styles: {
      light: {
        background: '#fdf4ff',
        foreground: '#4a044e',
        card: '#ffffff',
        'card-foreground': '#4a044e',
        popover: '#ffffff',
        'popover-foreground': '#4a044e',
        primary: '#d946ef',
        'primary-foreground': '#ffffff',
        secondary: '#f5d0fe',
        'secondary-foreground': '#86198f',
        muted: '#fae8ff',
        'muted-foreground': '#a21caf',
        accent: '#06b6d4',
        'accent-foreground': '#ffffff',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#e879f9',
        input: '#f5d0fe',
        ring: '#d946ef',
        radius: '0.25rem',
      },
      dark: {
        background: '#0f0011',
        foreground: '#fdf4ff',
        card: '#1a0020',
        'card-foreground': '#fdf4ff',
        popover: '#1a0020',
        'popover-foreground': '#fdf4ff',
        primary: '#f0abfc',
        'primary-foreground': '#4a044e',
        secondary: '#701a75',
        'secondary-foreground': '#fae8ff',
        muted: '#86198f',
        'muted-foreground': '#f5d0fe',
        accent: '#22d3ee',
        'accent-foreground': '#0f0011',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#a21caf',
        input: '#701a75',
        ring: '#f0abfc',
        radius: '0.25rem',
      },
    },
  },
  {
    id: 'pastel-dreams',
    label: 'Pastel Dreams',
    description: 'Soft lavender pastels',
    category: 'colorful',
    tags: ['pastel', 'lavender', 'soft', 'dreamy'],
    styles: {
      light: {
        background: '#fefcff',
        foreground: '#4c1d95',
        card: '#ffffff',
        'card-foreground': '#4c1d95',
        popover: '#ffffff',
        'popover-foreground': '#4c1d95',
        primary: '#a78bfa',
        'primary-foreground': '#ffffff',
        secondary: '#fde68a',
        'secondary-foreground': '#92400e',
        muted: '#f5f3ff',
        'muted-foreground': '#6d28d9',
        accent: '#93c5fd',
        'accent-foreground': '#1e3a8a',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#ddd6fe',
        input: '#f5f3ff',
        ring: '#a78bfa',
        radius: '1rem',
      },
      dark: {
        background: '#0f0a1a',
        foreground: '#f5f3ff',
        card: '#1e1533',
        'card-foreground': '#f5f3ff',
        popover: '#1e1533',
        'popover-foreground': '#f5f3ff',
        primary: '#c4b5fd',
        'primary-foreground': '#2e1065',
        secondary: '#451a03',
        'secondary-foreground': '#fde68a',
        muted: '#3b2470',
        'muted-foreground': '#ddd6fe',
        accent: '#1e3a8a',
        'accent-foreground': '#93c5fd',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#4c1d95',
        input: '#3b2470',
        ring: '#c4b5fd',
        radius: '1rem',
      },
    },
  },
  {
    id: 'ocean-breeze',
    label: 'Ocean Breeze',
    description: 'Teal/green aquatic',
    category: 'cool',
    tags: ['teal', 'green', 'ocean', 'aquatic'],
    styles: {
      light: {
        background: '#f0fdfa',
        foreground: '#0f172a',
        card: '#ffffff',
        'card-foreground': '#0f172a',
        popover: '#ffffff',
        'popover-foreground': '#0f172a',
        primary: '#0d9488',
        'primary-foreground': '#ffffff',
        secondary: '#e0f2fe',
        'secondary-foreground': '#0369a1',
        muted: '#f1f5f9',
        'muted-foreground': '#64748b',
        accent: '#5eead4',
        'accent-foreground': '#134e4a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#a7f3d0',
        input: '#e0f2fe',
        ring: '#0d9488',
        radius: '0.5rem',
      },
      dark: {
        background: '#042f2e',
        foreground: '#f0fdfa',
        card: '#115e59',
        'card-foreground': '#f0fdfa',
        popover: '#115e59',
        'popover-foreground': '#f0fdfa',
        primary: '#2dd4bf',
        'primary-foreground': '#042f2e',
        secondary: '#0c4a6e',
        'secondary-foreground': '#bae6fd',
        muted: '#0f766e',
        'muted-foreground': '#ccfbf1',
        accent: '#14b8a6',
        'accent-foreground': '#f0fdfa',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#0f766e',
        input: '#0c4a6e',
        ring: '#2dd4bf',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'claude',
    label: 'Claude',
    description: 'Warm taupe/copper theme',
    category: 'brand',
    tags: ['claude', 'taupe', 'copper', 'brand'],
    styles: {
      light: {
        background: '#fffaf5',
        foreground: '#1c1917',
        card: '#ffffff',
        'card-foreground': '#1c1917',
        popover: '#ffffff',
        'popover-foreground': '#1c1917',
        primary: '#d97706',
        'primary-foreground': '#ffffff',
        secondary: '#f5f5f4',
        'secondary-foreground': '#44403c',
        muted: '#fafaf9',
        'muted-foreground': '#78716c',
        accent: '#fed7aa',
        'accent-foreground': '#9a3412',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#e7e5e4',
        input: '#f5f5f4',
        ring: '#d97706',
        radius: '0.5rem',
      },
      dark: {
        background: '#1c1917',
        foreground: '#fafaf9',
        card: '#292524',
        'card-foreground': '#fafaf9',
        popover: '#292524',
        'popover-foreground': '#fafaf9',
        primary: '#fbbf24',
        'primary-foreground': '#1c1917',
        secondary: '#44403c',
        'secondary-foreground': '#fafaf9',
        muted: '#57534e',
        'muted-foreground': '#a8a29e',
        accent: '#78350f',
        'accent-foreground': '#fed7aa',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#44403c',
        input: '#57534e',
        ring: '#fbbf24',
        radius: '0.5rem',
      },
    },
  },
  {
    id: 'vercel',
    label: 'Vercel',
    description: 'Clean black & white',
    category: 'monochrome',
    tags: ['vercel', 'black', 'white', 'minimal'],
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#000000',
        card: '#fafafa',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#000000',
        'primary-foreground': '#ffffff',
        secondary: '#f5f5f5',
        'secondary-foreground': '#171717',
        muted: '#f5f5f5',
        'muted-foreground': '#737373',
        accent: '#f5f5f5',
        'accent-foreground': '#000000',
        destructive: '#ff0000',
        'destructive-foreground': '#ffffff',
        border: '#e5e5e5',
        input: '#f5f5f5',
        ring: '#000000',
        radius: '0.375rem',
      },
      dark: {
        background: '#000000',
        foreground: '#ffffff',
        card: '#0a0a0a',
        'card-foreground': '#ffffff',
        popover: '#0a0a0a',
        'popover-foreground': '#ffffff',
        primary: '#ffffff',
        'primary-foreground': '#000000',
        secondary: '#262626',
        'secondary-foreground': '#fafafa',
        muted: '#262626',
        'muted-foreground': '#a3a3a3',
        accent: '#262626',
        'accent-foreground': '#ffffff',
        destructive: '#ff4444',
        'destructive-foreground': '#ffffff',
        border: '#262626',
        input: '#262626',
        ring: '#ffffff',
        radius: '0.375rem',
      },
    },
  },
  {
    id: 'vintage-paper',
    label: 'Vintage Paper',
    description: 'Sepia aged aesthetic',
    category: 'retro',
    tags: ['vintage', 'sepia', 'paper', 'retro'],
    styles: {
      light: {
        background: '#fdf6e3',
        foreground: '#3c3836',
        card: '#f5eedc',
        'card-foreground': '#3c3836',
        popover: '#f5eedc',
        'popover-foreground': '#3c3836',
        primary: '#b58900',
        'primary-foreground': '#fdf6e3',
        secondary: '#eee8d5',
        'secondary-foreground': '#657b83',
        muted: '#eee8d5',
        'muted-foreground': '#93a1a1',
        accent: '#cb4b16',
        'accent-foreground': '#fdf6e3',
        destructive: '#dc322f',
        'destructive-foreground': '#fdf6e3',
        border: '#d3c6aa',
        input: '#eee8d5',
        ring: '#b58900',
        radius: '0.25rem',
      },
      dark: {
        background: '#002b36',
        foreground: '#fdf6e3',
        card: '#073642',
        'card-foreground': '#fdf6e3',
        popover: '#073642',
        'popover-foreground': '#fdf6e3',
        primary: '#b58900',
        'primary-foreground': '#002b36',
        secondary: '#586e75',
        'secondary-foreground': '#eee8d5',
        muted: '#073642',
        'muted-foreground': '#839496',
        accent: '#cb4b16',
        'accent-foreground': '#fdf6e3',
        destructive: '#dc322f',
        'destructive-foreground': '#fdf6e3',
        border: '#586e75',
        input: '#586e75',
        ring: '#b58900',
        radius: '0.25rem',
      },
    },
  },
]

// Helper to get presets by category
export function getPresetsByCategory(category: TweakcnPreset['category']): TweakcnPreset[] {
  return TWEAKCN_PRESETS.filter((p) => p.category === category)
}

// Helper to search presets
export function searchPresets(query: string): TweakcnPreset[] {
  const lowercaseQuery = query.toLowerCase()
  return TWEAKCN_PRESETS.filter(
    (p) =>
      p.label.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery))
  )
}

// Get all unique categories
export const PRESET_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'professional', label: 'Professional' },
  { id: 'colorful', label: 'Colorful' },
  { id: 'nature', label: 'Nature' },
  { id: 'warm', label: 'Warm' },
  { id: 'cool', label: 'Cool' },
  { id: 'brand', label: 'Brand' },
  { id: 'retro', label: 'Retro' },
  { id: 'monochrome', label: 'Monochrome' },
] as const
