import type { DesignSystemConfigInput } from '~/types/config'
import { generateNuxtUISetupScript } from './nuxtUIGenerator'
import { generateTailwindSetupScript } from './tailwindGenerator'

// ============================================
// shadcn-vue CLI Commands
// ============================================

// Generate shadcn-vue CLI init command
export function generateInitCommand(config: DesignSystemConfigInput): string {
  const style = config.components.style
  const typescript = config.export.typescript

  let command = 'npx shadcn-vue@latest init'

  // Add style flag
  if (style !== 'default') {
    command += ` --style ${style}`
  }

  // Add TypeScript flag
  if (!typescript) {
    command += ' --no-typescript'
  }

  return command
}

// Generate component add command
export function generateAddCommand(components: readonly string[]): string {
  if (components.length === 0) {
    return '# No components selected'
  }

  if (components.length === 1) {
    return `npx shadcn-vue@latest add ${components[0]}`
  }

  // For multiple components, format nicely
  return `npx shadcn-vue@latest add ${components.join(' ')}`
}

// Generate full setup script for shadcn-vue
export function generateSetupScript(config: DesignSystemConfigInput): string {
  const lines: string[] = [
    '#!/bin/bash',
    '',
    '# shadcn-vue Setup Script',
    '# Generated by Vueforge',
    '',
  ]

  // Framework-specific project creation
  if (config.export.framework === 'nuxt') {
    lines.push('# Create Nuxt project')
    lines.push('npx nuxi@latest init my-app')
    lines.push('cd my-app')
    lines.push('')
    lines.push('# Install Tailwind CSS v4')
    lines.push('npm install tailwindcss @tailwindcss/vite')
    lines.push('')
  } else {
    lines.push('# Create Vue project')
    lines.push('npm create vue@latest my-app')
    lines.push('cd my-app')
    lines.push('')
    lines.push('# Install Tailwind CSS v4')
    lines.push('npm install tailwindcss @tailwindcss/vite')
    lines.push('')
  }

  // Initialize shadcn-vue
  lines.push('# Initialize shadcn-vue')
  lines.push(generateInitCommand(config))
  lines.push('')

  // Add selected components
  if (config.export.includeComponents.length > 0) {
    lines.push('# Add components')
    lines.push(generateAddCommand(config.export.includeComponents))
    lines.push('')
  }

  lines.push('# Start development server')
  lines.push('npm run dev')

  return lines.join('\n')
}

// ============================================
// Universal Setup Script Generator
// ============================================

// Generate setup script based on UI library
export function generateUniversalSetupScript(config: DesignSystemConfigInput): string {
  const uiLibrary = config.export.uiLibrary

  switch (uiLibrary) {
    case 'nuxt-ui':
      return generateNuxtUISetupScript()
    case 'tailwind':
      return generateTailwindSetupScript(config)
    case 'shadcn-vue':
    default:
      return generateSetupScript(config)
  }
}

// Get the appropriate CLI commands based on UI library
export function getLibraryCommands(config: DesignSystemConfigInput): {
  init: string
  install?: string
  add?: string
} {
  const uiLibrary = config.export.uiLibrary

  switch (uiLibrary) {
    case 'nuxt-ui':
      return {
        init: 'npx nuxi@latest init my-app',
        install: 'npx nuxi module add ui',
      }
    case 'tailwind':
      return {
        init:
          config.export.framework === 'nuxt'
            ? 'npx nuxi@latest init my-app'
            : 'npm create vue@latest my-app',
        install: 'npm install tailwindcss @tailwindcss/vite',
      }
    case 'shadcn-vue':
    default:
      return {
        init: generateInitCommand(config),
        add:
          config.export.includeComponents.length > 0
            ? generateAddCommand(config.export.includeComponents)
            : undefined,
      }
  }
}

// Generate components.json configuration for CLI
export function generateCLIComponentsJson(config: DesignSystemConfigInput): string {
  const componentsConfig = {
    $schema: 'https://shadcn-vue.com/schema.json',
    style: config.components.style,
    typescript: config.export.typescript,
    tailwind: {
      config: config.export.framework === 'nuxt' ? '' : 'tailwind.config.js',
      css: config.export.framework === 'nuxt' ? 'assets/css/main.css' : 'src/assets/main.css',
      baseColor: config.theme.baseColor,
      cssVariables: true,
    },
    aliases: {
      utils: config.export.framework === 'nuxt' ? '~/lib/utils' : '@/lib/utils',
      components: config.export.framework === 'nuxt' ? '~/components' : '@/components',
      ui: config.export.framework === 'nuxt' ? '~/components/ui' : '@/components/ui',
    },
  }

  return JSON.stringify(componentsConfig, null, 2)
}

// Generate package.json dependencies
export function generateDependencies(): Record<string, string> {
  return {
    'class-variance-authority': '^0.7.0',
    clsx: '^2.1.0',
    'reka-ui': '^2.0.0',
    'tailwind-merge': '^2.6.0',
  }
}

// Generate dev dependencies
export function generateDevDependencies(): Record<string, string> {
  return {
    tailwindcss: '^4.0.0',
    '@tailwindcss/vite': '^4.0.0',
  }
}
