import type { DesignSystemConfigInput, ThemeName } from '~/types/config'
import { getThemeColors } from '~/config/themes'

// Map our theme names to Nuxt UI / Tailwind color names
const THEME_TO_TAILWIND_COLOR: Record<ThemeName, string> = {
  neutral: 'neutral',
  stone: 'stone',
  zinc: 'zinc',
  gray: 'gray',
  slate: 'slate',
  red: 'red',
  rose: 'rose',
  orange: 'orange',
  amber: 'amber',
  yellow: 'yellow',
  lime: 'lime',
  green: 'green',
  emerald: 'emerald',
  teal: 'teal',
  cyan: 'cyan',
  sky: 'sky',
  blue: 'blue',
  indigo: 'indigo',
  violet: 'violet',
  purple: 'purple',
  fuchsia: 'fuchsia',
  pink: 'pink',
}

// Get the Tailwind color name for a theme
export function getTailwindColorName(theme: ThemeName): string {
  return THEME_TO_TAILWIND_COLOR[theme] || 'blue'
}

// Generate app.config.ts for Nuxt UI
export function generateNuxtUIAppConfig(config: DesignSystemConfigInput): string {
  const primaryColor = getTailwindColorName(config.theme.accentTheme)
  const neutralColor = getTailwindColorName(config.theme.baseColor)

  return `export default defineAppConfig({
  ui: {
    colors: {
      primary: '${primaryColor}',
      neutral: '${neutralColor}',
    },
  },
})
`
}

// Generate nuxt.config.ts additions for Nuxt UI
export function generateNuxtUIConfig(config: DesignSystemConfigInput): string {
  return `// Add to your nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@nuxt/ui'],
  ui: {
    theme: {
      colors: ['primary', 'secondary', 'info', 'success', 'warning', 'error'],
    },
  },
  // Optional: Configure fonts
  fonts: {
    families: [
      { name: '${config.typography.fontFamily}', provider: 'google' },
    ],
  },
})
`
}

// Generate CSS variables for Nuxt UI
export function generateNuxtUICSS(config: DesignSystemConfigInput): string {
  const colors = getThemeColors(config.theme.baseColor, config.theme.accentTheme)

  // Nuxt UI uses --ui-* prefix for its CSS variables
  return `@import "tailwindcss";

/* Nuxt UI Custom Theme */
/* These CSS variables override the default Nuxt UI theme */

:root {
  /* Primary color shade overrides */
  --ui-primary: var(--ui-color-primary-500);

  /* Custom radius */
  --ui-radius: ${getRadiusValue(config.theme.radius)};

  /* Font family */
  --ui-font-sans: ${getFontFamily(config.typography.fontFamily)};
}

.dark {
  --ui-primary: var(--ui-color-primary-400);
}

/* Additional customizations based on your design system */
:root {
  /* Chart colors mapped from your theme */
  --color-chart-1: ${colors.light.chart1};
  --color-chart-2: ${colors.light.chart2};
  --color-chart-3: ${colors.light.chart3};
  --color-chart-4: ${colors.light.chart4};
  --color-chart-5: ${colors.light.chart5};
}

.dark {
  --color-chart-1: ${colors.dark.chart1};
  --color-chart-2: ${colors.dark.chart2};
  --color-chart-3: ${colors.dark.chart3};
  --color-chart-4: ${colors.dark.chart4};
  --color-chart-5: ${colors.dark.chart5};
}
`
}

// Generate setup instructions for Nuxt UI
export function generateNuxtUISetupScript(): string {
  return `#!/bin/bash

# Nuxt UI Setup Script
# Generated by Vuecraft

# Create new Nuxt project
npx nuxi@latest init my-app
cd my-app

# Add Nuxt UI module
npx nuxi module add ui

# Install dependencies
npm install

# Start development server
npm run dev
`
}

// Generate CLI commands for Nuxt UI
export function generateNuxtUICommands(): {
  install: string
  moduleAdd: string
} {
  return {
    install: 'npx nuxi@latest init my-app && cd my-app',
    moduleAdd: 'npx nuxi module add ui',
  }
}

// Generate full export package for Nuxt UI
export function generateNuxtUIExportPackage(config: DesignSystemConfigInput): {
  appConfig: string
  nuxtConfig: string
  css: string
  readme: string
} {
  const appConfig = generateNuxtUIAppConfig(config)
  const nuxtConfig = generateNuxtUIConfig(config)
  const css = generateNuxtUICSS(config)

  const readme = `# Nuxt UI Theme Configuration

This theme was generated using Vuecraft.

## Configuration

- **Primary Color**: ${config.theme.accentTheme}
- **Neutral Color**: ${config.theme.baseColor}
- **Border Radius**: ${config.theme.radius}
- **Font Family**: ${config.typography.fontFamily}

## Installation

### 1. Create a new Nuxt project (or use existing)

\`\`\`bash
npx nuxi@latest init my-app
cd my-app
\`\`\`

### 2. Add Nuxt UI module

\`\`\`bash
npx nuxi module add ui
\`\`\`

### 3. Configure your app

Copy the contents of \`app.config.ts\` to your project's \`app.config.ts\`:

\`\`\`typescript
${appConfig}\`\`\`

### 4. Add custom CSS (optional)

If you want additional customizations, copy the CSS to your \`assets/css/main.css\`.

## Files Included

- \`app.config.ts\` - Nuxt UI color configuration
- \`nuxt.config.ts\` - Module configuration reference
- \`main.css\` - Optional CSS customizations

## Documentation

- [Nuxt UI Documentation](https://ui.nuxt.com)
- [Nuxt UI Theming](https://ui.nuxt.com/getting-started/theme)
`

  return { appConfig, nuxtConfig, css, readme }
}

// Helper functions
function getRadiusValue(radius: string): string {
  const radiusMap: Record<string, string> = {
    none: '0',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  }
  return radiusMap[radius] || '0.375rem'
}

function getFontFamily(font: string): string {
  const fontMap: Record<string, string> = {
    inter: '"Inter", ui-sans-serif, system-ui, sans-serif',
    'noto-sans': '"Noto Sans", ui-sans-serif, system-ui, sans-serif',
    'nunito-sans': '"Nunito Sans", ui-sans-serif, system-ui, sans-serif',
    figtree: '"Figtree", ui-sans-serif, system-ui, sans-serif',
    roboto: '"Roboto", ui-sans-serif, system-ui, sans-serif',
    raleway: '"Raleway", ui-sans-serif, system-ui, sans-serif',
    'dm-sans': '"DM Sans", ui-sans-serif, system-ui, sans-serif',
    'public-sans': '"Public Sans", ui-sans-serif, system-ui, sans-serif',
    outfit: '"Outfit", ui-sans-serif, system-ui, sans-serif',
    geist: '"Geist", ui-sans-serif, system-ui, sans-serif',
  }
  return fontMap[font] ?? fontMap['inter']!
}
