import type { DesignSystemConfigInput, RadiusValue, ShadowIntensity } from '~/types/config'
import { getThemeColors } from '~/config/themes'
import { RADIUS_OPTIONS } from '~/config/defaults'

// Font family mappings
const FONT_FAMILY_MAP: Record<string, string> = {
  inter: '"Inter", ui-sans-serif, system-ui, sans-serif',
  'noto-sans': '"Noto Sans", ui-sans-serif, system-ui, sans-serif',
  'nunito-sans': '"Nunito Sans", ui-sans-serif, system-ui, sans-serif',
  figtree: '"Figtree", ui-sans-serif, system-ui, sans-serif',
  roboto: '"Roboto", ui-sans-serif, system-ui, sans-serif',
  raleway: '"Raleway", ui-sans-serif, system-ui, sans-serif',
  'dm-sans': '"DM Sans", ui-sans-serif, system-ui, sans-serif',
  'public-sans': '"Public Sans", ui-sans-serif, system-ui, sans-serif',
  outfit: '"Outfit", ui-sans-serif, system-ui, sans-serif',
  geist: '"Geist", ui-sans-serif, system-ui, sans-serif',
}

const MONO_FONT_FAMILY_MAP: Record<string, string> = {
  'jetbrains-mono': '"JetBrains Mono", ui-monospace, monospace',
  'geist-mono': '"Geist Mono", ui-monospace, monospace',
  'fira-code': '"Fira Code", ui-monospace, monospace',
  'source-code-pro': '"Source Code Pro", ui-monospace, monospace',
}

// Get radius value
function getRadiusValue(radius: RadiusValue): string {
  const option = RADIUS_OPTIONS.find((r) => r.name === radius)
  return option?.value ?? '0.5rem'
}

// Get shadow values based on intensity
function getShadowValues(intensity: ShadowIntensity): {
  sm: string
  md: string
  lg: string
  xl: string
} {
  switch (intensity) {
    case 'none':
      return {
        sm: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
      }
    case 'subtle':
      return {
        sm: '0 1px 1px 0 rgb(0 0 0 / 0.03)',
        md: '0 2px 3px -1px rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)',
        lg: '0 4px 6px -2px rgb(0 0 0 / 0.05), 0 2px 3px -2px rgb(0 0 0 / 0.05)',
        xl: '0 8px 10px -3px rgb(0 0 0 / 0.05), 0 4px 5px -3px rgb(0 0 0 / 0.05)',
      }
    case 'default':
      return {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      }
    case 'strong':
      return {
        sm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 6px 10px -2px rgb(0 0 0 / 0.15), 0 3px 6px -3px rgb(0 0 0 / 0.15)',
        lg: '0 15px 20px -5px rgb(0 0 0 / 0.15), 0 6px 8px -6px rgb(0 0 0 / 0.15)',
        xl: '0 25px 35px -8px rgb(0 0 0 / 0.2), 0 10px 15px -8px rgb(0 0 0 / 0.15)',
      }
  }
}

// Generate minimal CSS for plain Tailwind (no component library)
export function generateTailwindCSS(config: DesignSystemConfigInput): string {
  const colors = getThemeColors(config.theme.baseColor, config.theme.accentTheme)
  const radius = getRadiusValue(config.theme.radius)
  const shadows = getShadowValues(config.theme.shadowIntensity)
  const fontFamily = FONT_FAMILY_MAP[config.typography.fontFamily] ?? FONT_FAMILY_MAP['inter']
  const monoFontFamily =
    MONO_FONT_FAMILY_MAP[config.typography.monoFontFamily] ?? MONO_FONT_FAMILY_MAP['jetbrains-mono']

  return `@import "tailwindcss";

/*
 * Plain Tailwind CSS Theme
 * Generated by Vuecraft
 *
 * These CSS variables can be used with Tailwind CSS v4's @theme directive
 * or directly in your CSS.
 */

@theme {
  /* Colors */
  --color-primary: var(--color-primary);
  --color-primary-foreground: var(--color-primary-foreground);
  --color-secondary: var(--color-secondary);
  --color-secondary-foreground: var(--color-secondary-foreground);
  --color-accent: var(--color-accent);
  --color-accent-foreground: var(--color-accent-foreground);
  --color-muted: var(--color-muted);
  --color-muted-foreground: var(--color-muted-foreground);
  --color-background: var(--color-background);
  --color-foreground: var(--color-foreground);
  --color-border: var(--color-border);
  --color-ring: var(--color-ring);

  /* Radius */
  --radius-sm: var(--radius-sm);
  --radius-md: var(--radius-md);
  --radius-lg: var(--radius-lg);
  --radius-xl: var(--radius-xl);

  /* Fonts */
  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);
}

:root {
  /* Base Variables */
  --radius: ${radius};
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);

  /* Fonts */
  --font-sans: ${fontFamily};
  --font-mono: ${monoFontFamily};

  /* Shadows */
  --shadow-sm: ${shadows.sm};
  --shadow-md: ${shadows.md};
  --shadow-lg: ${shadows.lg};
  --shadow-xl: ${shadows.xl};

  /* Light Mode Colors */
  --color-background: ${colors.light.background};
  --color-foreground: ${colors.light.foreground};
  --color-primary: ${colors.light.primary};
  --color-primary-foreground: ${colors.light.primaryForeground};
  --color-secondary: ${colors.light.secondary};
  --color-secondary-foreground: ${colors.light.secondaryForeground};
  --color-accent: ${colors.light.accent};
  --color-accent-foreground: ${colors.light.accentForeground};
  --color-muted: ${colors.light.muted};
  --color-muted-foreground: ${colors.light.mutedForeground};
  --color-border: ${colors.light.border};
  --color-input: ${colors.light.input};
  --color-ring: ${colors.light.ring};
  --color-destructive: ${colors.light.destructive};
  --color-destructive-foreground: ${colors.light.destructiveForeground};

  /* Chart Colors */
  --color-chart-1: ${colors.light.chart1};
  --color-chart-2: ${colors.light.chart2};
  --color-chart-3: ${colors.light.chart3};
  --color-chart-4: ${colors.light.chart4};
  --color-chart-5: ${colors.light.chart5};
}

.dark {
  /* Dark Mode Colors */
  --color-background: ${colors.dark.background};
  --color-foreground: ${colors.dark.foreground};
  --color-primary: ${colors.dark.primary};
  --color-primary-foreground: ${colors.dark.primaryForeground};
  --color-secondary: ${colors.dark.secondary};
  --color-secondary-foreground: ${colors.dark.secondaryForeground};
  --color-accent: ${colors.dark.accent};
  --color-accent-foreground: ${colors.dark.accentForeground};
  --color-muted: ${colors.dark.muted};
  --color-muted-foreground: ${colors.dark.mutedForeground};
  --color-border: ${colors.dark.border};
  --color-input: ${colors.dark.input};
  --color-ring: ${colors.dark.ring};
  --color-destructive: ${colors.dark.destructive};
  --color-destructive-foreground: ${colors.dark.destructiveForeground};

  /* Chart Colors */
  --color-chart-1: ${colors.dark.chart1};
  --color-chart-2: ${colors.dark.chart2};
  --color-chart-3: ${colors.dark.chart3};
  --color-chart-4: ${colors.dark.chart4};
  --color-chart-5: ${colors.dark.chart5};
}

/* Base Styles */
* {
  border-color: var(--color-border);
}

body {
  background-color: var(--color-background);
  color: var(--color-foreground);
  font-family: var(--font-sans);
}
`
}

// Generate setup instructions for plain Tailwind
export function generateTailwindSetupScript(config: DesignSystemConfigInput): string {
  const isNuxt = config.export.framework === 'nuxt'

  if (isNuxt) {
    return `#!/bin/bash

# Tailwind CSS v4 Setup for Nuxt
# Generated by Vuecraft

# Create new Nuxt project
npx nuxi@latest init my-app
cd my-app

# Install Tailwind CSS v4
npm install tailwindcss @tailwindcss/vite

# Add Tailwind to your Nuxt config (nuxt.config.ts):
# vite: {
#   plugins: [tailwindcss()]
# }

# Copy the generated CSS to assets/css/main.css
# Import it in your nuxt.config.ts:
# css: ['~/assets/css/main.css']

# Start development
npm run dev
`
  }

  return `#!/bin/bash

# Tailwind CSS v4 Setup for Vue
# Generated by Vuecraft

# Create new Vue project
npm create vue@latest my-app
cd my-app

# Install Tailwind CSS v4
npm install tailwindcss @tailwindcss/vite

# Add Tailwind to your Vite config (vite.config.ts):
# import tailwindcss from '@tailwindcss/vite'
# plugins: [vue(), tailwindcss()]

# Copy the generated CSS to src/assets/main.css
# Import it in your main.ts

# Start development
npm run dev
`
}

// Generate full export package for plain Tailwind
export function generateTailwindExportPackage(config: DesignSystemConfigInput): {
  css: string
  setupScript: string
  readme: string
} {
  const css = generateTailwindCSS(config)
  const setupScript = generateTailwindSetupScript(config)

  const readme = `# Plain Tailwind CSS Theme

This theme was generated using Vuecraft.

## Configuration

- **Primary Color**: ${config.theme.accentTheme}
- **Base Color**: ${config.theme.baseColor}
- **Border Radius**: ${config.theme.radius}
- **Shadow Intensity**: ${config.theme.shadowIntensity}
- **Font Family**: ${config.typography.fontFamily}
- **Mono Font**: ${config.typography.monoFontFamily}

## Installation

### For ${config.export.framework === 'nuxt' ? 'Nuxt' : 'Vue (Vite)'}

1. Install Tailwind CSS v4:
   \`\`\`bash
   npm install tailwindcss @tailwindcss/vite
   \`\`\`

2. ${config.export.framework === 'nuxt' ? 'Add to your nuxt.config.ts' : 'Add to your vite.config.ts'}:
   \`\`\`typescript
   import tailwindcss from '@tailwindcss/vite'

   // In plugins array:
   plugins: [tailwindcss()]
   \`\`\`

3. Copy \`main.css\` to your assets folder

4. Import the CSS in your app

## Usage

The theme provides CSS variables that work with Tailwind CSS v4:

\`\`\`html
<!-- Use with Tailwind classes -->
<div class="bg-background text-foreground">
  <button class="bg-primary text-primary-foreground rounded-lg">
    Click me
  </button>
</div>

<!-- Or use CSS variables directly -->
<style>
.custom-element {
  background: var(--color-primary);
  border-radius: var(--radius-lg);
}
</style>
\`\`\`

## Available Variables

### Colors
- \`--color-background\` / \`--color-foreground\`
- \`--color-primary\` / \`--color-primary-foreground\`
- \`--color-secondary\` / \`--color-secondary-foreground\`
- \`--color-accent\` / \`--color-accent-foreground\`
- \`--color-muted\` / \`--color-muted-foreground\`
- \`--color-border\`, \`--color-input\`, \`--color-ring\`
- \`--color-destructive\` / \`--color-destructive-foreground\`
- \`--color-chart-1\` through \`--color-chart-5\`

### Layout
- \`--radius-sm\`, \`--radius-md\`, \`--radius-lg\`, \`--radius-xl\`
- \`--shadow-sm\`, \`--shadow-md\`, \`--shadow-lg\`, \`--shadow-xl\`

### Typography
- \`--font-sans\`
- \`--font-mono\`

## Files Included

- \`main.css\` - Theme CSS with Tailwind CSS v4 configuration
- \`setup.sh\` - Installation script
`

  return { css, setupScript, readme }
}
